#strong[Background:] Genomic pathogenicity prediction is dominated by variant-category annotation (nonsense, frameshift, intronic, synonymous), which produces high pooled accuracy that can be mistaken for independent structural or mechanistic evidence. We use a physics-based 3D chromatin loop-extrusion classifier (ARCHCODE) as a test case to systematically decompose how much of a headline accuracy score is attributable to category composition versus genuine within-category discrimination.

#strong[Methods:] We analyzed 26,225 ClinVar variants across 9 clinically important genomic loci (HBB, TP53, BRCA1, MLH1, TERT, GJB2, CFTR, GATA1, PTEN), applying falsification-first controls: a position-only ablation (category information removed), within-category AUC stratified across 25 category-locus combinations, category-and-locus-matched control comparisons for candidate architecture-driven variants, a permutation test for a category-independent geometric feature (enhancer proximity), and independent orthogonal validation via AlphaGenome CAGE-seq promoter-activity predictions at the tissue-matched HBB locus.

#strong[Results:] The pooled HBB AUC of 0.977 collapses to 0.551 (near chance) when category information is removed, and the median within-category AUC across 25 category-locus combinations is 0.52 — indistinguishable from chance. Only one combination (TP53 splice_region, AUC=0.69, Cohen's d=−0.78, FDR-corrected) shows a surviving within-category signal. At the four best-covered non-HBB loci (BRCA1, CFTR, LDLR, MLH1), the 27 candidate architecture-driven ("Class B") variants do not separate from category-and-locus-matched benign controls (pooled Mann–Whitney p=0.996, Cohen's d=−0.52; 0/6 per-locus tests significant). In contrast, at the tissue-matched HBB locus, a category-independent geometric feature — proximity to tissue-matched enhancers among candidate architecture-driven (Q2b) variants — remains significant after permutation testing (odds ratio=34.05 at 500 bp; 10,000-shuffle permutation p&lt;0.0001; Cohen's d=−1.63; robust across LSSIM thresholds 0.92–0.98). Independent AlphaGenome CAGE-seq validation at HBB is directionally convergent: pearl variants show 5.5-fold greater predicted promoter-accessibility disruption than pathogenic non-pearls (Mann–Whitney p=4×10⁻⁶, Cohen's d=−2.1), though we flag substantial pseudoreplication (11 of 12 tested positions cluster within a 73 bp promoter region, reducing effective independent observations to ≈2–3) and therefore emphasize effect size over formal significance.

#strong[Conclusions:] Pooled accuracy metrics for structure-based pathogenicity scoring are primarily driven by variant-category composition, not independent 3D structural discrimination — a confound likely shared by any tool that conditions perturbation strength on sequence-derived category labels. We could not confirm that ARCHCODE's chromatin-simulation score discriminates pathogenic from benign variants within a matched category and locus. The one signal that survives every control applied — enhancer-proximity enrichment, a purely geometric feature independent of the category confound — is the paper's most defensible finding and the recommended object of future validation. We report this as an explicit falsification of our own headline metric, consistent with a falsification-first, honest-null-result methodology.

#strong[Keywords:] 3D chromatin structure, variant pathogenicity, loop extrusion, falsification methodology, category confound, within-category AUC, AlphaGenome, ClinVar, ARCHCODE
