#strong[Background:] Category annotation saturates genomic pathogenicity prediction signal — we demonstrate this fundamental limit using systematic 3D chromatin structure analysis and explain the mechanism through Simpson's Paradox and orthogonal model comparison.

#strong[Methods:] We tested six hypotheses linking 3D chromatin structure to variant pathogenicity across 26,225 variants from 9 genomic loci (HBB, TP53, BRCA1, MLH1, TERT, GJB2, CFTR, GATA1, PTEN), applying falsification-first methodology with pre-registered kill criteria, category-matched controls, and independent AlphaGenome CAGE validation.

#strong[Results:] Variant category alone achieves pooled AUC=0.791, but Simpson's Paradox reveals this masks within-category structural signal (intronic AUC=0.640, synonymous AUC=0.657). We tested AlphaGenome CAGE for mechanism-specific signal in HBB pilot + 6 exploratory loci. The HBB pilot is robust: pathogenic variants reduce accessibility 5.4-fold versus benign (p=4×10⁻⁶, Cohen's d=−1.53), surviving Bonferroni correction (α=0.007 for 7 tests). Exploratory extensions show mechanism-appropriate trends — 3 regulatory loci (MLH1 p=0.022 nominal, TERT hotspots +33-53% CAGE) directionally consistent with HBB, 4 coding loci (TP53, BRCA1, CFTR, GJB2; p>0.40) null as expected — but only HBB survived multiple-testing correction (1/4 robust). The null concordance between 3D structure and 1D accessibility models (ρ=0.014) demonstrates complementary biology: ARCHCODE captures loop-mediated effects, AlphaGenome captures open-chromatin accessibility — orthogonal mechanisms, not redundant information.

#strong[Conclusions:] Category annotation encodes ~80% of pathogenicity signal, establishing an upper bound (AUC~0.80) for genomic predictors and explaining why existing methods plateau. Simpson's Paradox demonstrates that pooled metrics mask mechanism-specific signals detectable through within-category stratification. The HBB pilot demonstrates that AlphaGenome CAGE can identify mechanism-specific regulatory disruption when ground truth is available; the 6-locus extension is exploratory and requires confirmation in larger cohorts. Our findings suggest reframing chromatin models as mechanism #emph[validators] (regulatory vs coding) rather than universal #emph[predictors], and pre-registering loci selection to avoid garden-of-forking-paths bias (Gelman & Loken, 2013). The framework's value lies in systematic falsification, honest null-result reporting, and identification of prediction limits to guide future multi-modal approaches.

#strong[Keywords:] 3D chromatin structure, variant pathogenicity, loop extrusion, falsification methodology, Simpson's Paradox, AlphaGenome, consilience, Bonferroni correction, ClinVar, ARCHCODE
