#strong[Background:] Sequence-based variant effect predictors (VEP)
evaluate pathogenicity through protein-coding impact and splice motif
disruption, but structurally-mediated effects on 3D chromatin topology
remain outside their scope. Variants acting through loop extrusion
disruption --- particularly in non-coding regulatory regions --- may be
systematically invisible to sequence analysis. We hypothesized that an
analytical simulation of cohesin-driven loop extrusion would reveal
pathogenic signal in HBB variants where standard VEP scores remain
uninformative.

#strong[Methods:] We retrieved 353 clinically classified HBB variants
from ClinVar via NCBI E-utilities API (April 2026 snapshot).
Sequence-based predictions were generated using Ensembl VEP v113 with
SIFT scoring. Structural predictions were generated by ARCHCODE, an
analytical mean-field loop extrusion simulator implementing Kramer
kinetics for cohesin barrier crossing (parameters: α=0.92, γ=0.80;
manually calibrated to published literature ranges from Gerlich et al.,
2006; Hansen et al., 2017; Sabaté et al., 2024). We extended the
analysis to CFTR (chr7, 317 kb TAD, 3,349 ClinVar variants: 1,756
Pathogenic/LP + 1,593 Benign/LB) to test cross-gene generalization at a
locus with greater variant positional diversity (201.5 kb spread, 63.6%
of TAD), TP53 (chr17, 300 kb TAD, 2,794 variants: 1,645 P/LP + 1,149
B/LB), BRCA1 (chr17, 400 kb TAD, 10,682 variants: 7,062 P/LP + 3,620
B/LB) --- the largest ClinVar cohort among loci tested, and MLH1 (chr3,
300 kb TAD, 4,060 variants: 2,425 P/LP + 1,635 B/LB) --- the first DNA
mismatch repair gene, associated with Lynch syndrome. Variant functional
classification was improved by determining frameshift vs inframe status
from cDNA indel length modulo 3. For each variant, ARCHCODE computed a
Structural Similarity Index (SSIM) comparing wild-type and mutant
predicted contact maps. To address matrix-size dilution --- where SSIM
dynamic range compresses on larger matrices (300×300 to 400×400) due to
decreasing perturbation fraction --- we introduced Local SSIM (LSSIM):
SSIM computed on a 50×50 submatrix centered on the variant bin,
normalizing perturbation fraction to \~12% regardless of total matrix
size. This enables direct threshold transfer from the calibrated HBB
30kb locus. Pre-defined thresholds (applied to LSSIM) classified
variants as: PATHOGENIC (LSSIM \< 0.85), LIKELY\_PATHOGENIC
(0.85--0.92), VUS (0.92--0.96), LIKELY\_BENIGN (0.96--0.99), BENIGN (≥
0.99). Discordance analysis identified "pearl" variants: VEP-blind (VEP
score \< 0.30) yet structurally disruptive (LSSIM \< 0.95).

#strong[Results:] Across nine loci --- HBB (1,103), CFTR (3,349), TP53
(2,794), BRCA1 (10,682), MLH1 (4,060), LDLR (3,284), SCN5A (2,488), TERT
(2,089), and GJB2 (469) --- ARCHCODE processed 30,318 ClinVar variants
through a unified label-blind simulation engine. Of 353 HBB variants
analyzed, ARCHCODE classified 161 (45.6%) as pathogenic (PATHOGENIC +
LIKELY\_PATHOGENIC combined). Structural classification correlated
strongly with functional variant category: loss-of-function classes
showed near-complete pathogenic assignment (nonsense: 40/40, 100%, mean
SSIM = 0.8753; frameshift: 99/99, 100%, mean SSIM = 0.8919;
splice\_acceptor: 3/3, 100%, mean SSIM = 0.9019; splice\_donor: 19/22,
86%, mean SSIM = 0.9087), while sequence-neutral classes were correctly
assigned as benign (synonymous: mean SSIM = 0.9989, 0/3 pathogenic;
intronic: mean SSIM = 0.9957, 0/9 pathogenic). Missense variants showed
intermediate structural preservation (mean SSIM = 0.9526, 0/125
pathogenic by structural threshold alone).

Discordance analysis identified 27 "pearl" variants where VEP provided
no signal (VEP \< 0.30) but ARCHCODE detected structural disruption
(SSIM \< 0.95). Integrative benchmarking with CADD v1.7 across 20,029
scored variants (66.1% coverage) confirms that 17 pearl variants occupy
a unique niche: VEP-blind (score ≤ 0.20), CADD-ambiguous (phred 10--20),
yet ARCHCODE-positive --- structural disruption detectable only through
chromatin simulation.

Distance analysis across all 30,318 variants reveals that enhancer
proximity is the primary driver of ARCHCODE structural discrimination:
variants within 1 kb of enhancers show 7-fold greater pathogenic-benign
separation (Δ LSSIM = 0.039) than the genome-wide average (Δ = 0.006).
Pearl variants cluster near enhancers (median 831 bp) rather than CTCF
sites (median 22,120 bp; Mann-Whitney p = 1.08 × 10⁻⁸), establishing
that ARCHCODE detects enhancer-proximal structural perturbation, not
CTCF barrier disruption. Per-locus threshold calibration demonstrates
that the universal 0.95 threshold is HBB-specific; locus-calibrated
thresholds (FPR ≤ 1%) improve sensitivity from 79.6% to 92.9% for HBB
(threshold = 0.977) while maintaining specificity. A tissue-specificity
gradient across nine loci confirms that ARCHCODE discrimination requires
tissue-matched epigenomic annotation: HBB (matched, Δ = 0.111), TERT
(expressed, Δ = 0.019), partial-match loci (Δ = 0.002--0.009), and two
intentional tissue-mismatch negative controls --- SCN5A (cardiac, Δ =
0.003) and GJB2 (cochlear, Δ = 0.006) --- both producing null results as
expected.

ROC analysis on an expanded cohort including 750 Benign/Likely Benign
HBB variants (total n=1,103), with all variants processed through a
single unified TypeScript simulation engine, yielded AUC = 0.977
(Pathogenic mean SSIM = 0.927; Benign mean SSIM = 0.996). Youden optimal
threshold (SSIM \< 0.994) achieved sensitivity = 0.966 and specificity =
0.988. The high AUC reflects category-distribution differences between
Pathogenic and Benign cohorts, not independent sequence-based
prediction. Formal within-category testing (logistic regression,
Mann--Whitney U, permutation) confirms that SSIM does not add
significant predictive value beyond category assignment on this locus (p
\= 1.0 for SSIM additive term), consistent with all 1,103 ClinVar
variants clustering within 2.1 kb (2.2% of the 95 kb window).

Cross-gene within-category testing using LSSIM yielded null results at
two loci: CFTR (3,349 variants, ΔAUC = −0.012, p = 0.79) and TP53 (2,794
variants, ΔAUC = +0.032, p = 0.29). Two larger loci showed statistically
significant but clinically negligible additive signal: BRCA1 (10,682
variants, ΔAUC = +0.002, p = 1.1×10⁻²⁰) and MLH1 (4,060 variants, ΔAUC =
\+0.011, p = 4.7×10⁻³). The BRCA1 and MLH1 significance reflects
statistical power at large sample sizes rather than meaningful
positional prediction (ΔAUC \< 0.02 in both cases). LSSIM expanded the
dynamic range from 0.98--1.00 (global SSIM) to 0.75--1.00, enabling
verdict assignment across all loci. Hi-C correlation varied by locus:
MLH1 K562 r = 0.59, BRCA1 K562 r = 0.53, MCF7 r = 0.50; LDLR HepG2 r =
0.32; TP53 K562 r = 0.29, MCF7 r = 0.28. Bayesian parameter optimization
(Optuna GPSampler, 200 trials) confirmed that kinetics parameters (α, γ,
k\_base) are near-optimal: Δr = +0.0001. All three parameters converged
to lower bounds, revealing that Hi-C correlation is architecture-driven
(distance decay, CTCF barriers, MED1 landscape), not kinetics-driven.

Hi-C correlation validation against K562 erythroid chromatin (4DN Data
Portal, KR-balanced, 1 kb resolution) yielded Pearson r = 0.53 (p =
2.2×10⁻⁸², n = 1,124 loci) for the original 30 kb window and r = 0.59 (p
\< 10⁻³⁰⁰, n = 11,649 loci) for an extended 95 kb sub-TAD window
anchored by ENCODE K562 CTCF peaks (3'HS1 and HS5). A prior attempt
using GM12878 lymphoblastoid Hi-C (r = 0.16, p = 0.30, n = 12) was not
significant, consistent with HBB being transcriptionally silent in
B-cells.

#strong[Conclusions:] ARCHCODE's analytical mean-field approach to loop
extrusion simulation identifies enhancer-proximal structural pathogenic
signal undetectable by sequence-based prediction across nine genomic
loci. The 27 HBB pearl variants represent candidates for experimental
prioritization. The key mechanistic insight --- that structural
discrimination concentrates at enhancer-proximal positions (≤1 kb) and
requires tissue-matched epigenomic annotation --- defines both the power
and the domain of applicability of chromatin simulation for variant
interpretation. We do not claim superiority over VEP or CADD; instead,
we propose structural simulation as a complementary,
hypothesis-generating layer that reveals a dimension of pathogenicity
invisible to sequence-based tools.

#strong[Limitations:]

- GM12878 Hi-C: r = 0.16 (ns); K562 Hi-C: r = 0.53--0.59 (p \< 10⁻⁸²)
- Analytical mean-field model; not full stochastic simulation
- Kramer kinetics parameters (α, γ) are manually calibrated, not fitted
  to experimental data
- VEP used instead of SpliceAI (API unreachable during study period)
- Pearl variants require experimental validation before clinical use
- No experimental RNA or protein data confirming predicted effects
- AUC = 0.977 reflects category-distribution differences, not
  independent prediction
- Within-category SSIM adds no predictive value beyond category on HBB
  (all variants in 2.1 kb cluster)
- CFTR within-category (LSSIM): ΔAUC = −0.012 (p = 0.79); null result
  with expanded dynamic range
- TP53 within-category (LSSIM): ΔAUC = +0.032 (p = 0.29); null result at
  300 kb TAD
- BRCA1 within-category (LSSIM): ΔAUC = +0.002 (p = 1.1×10⁻²⁰);
  statistically significant but ΔAUC negligible (power effect at
  n=10,682)
- Bayesian optimization (Optuna, 200 trials): Δr = 0.0001; kinetics
  params confirmed near-optimal
- Hi-C correlation locus-dependent: MLH1 r = 0.59; BRCA1 r = 0.50--0.53;
  TP53 r = 0.28--0.29 (lower, sparser contact map)
- MLH1 within-category (LSSIM): ΔAUC = +0.011 (p = 4.7×10⁻³);
  statistically significant but ΔAUC negligible (power effect at
  n=4,060)

#strong[Keywords:] β-thalassemia, HBB, chromatin loops, loop extrusion,
cohesin, SSIM, structural pathogenicity predictor, VEP, regulatory
variants, promoter variants, pearl variants, variant interpretation,
mean-field simulation, CFTR, TP53, BRCA1, MLH1, LDLR, SCN5A, TERT, GJB2,
Lynch syndrome, familial hypercholesterolemia, multi-locus validation,
Bayesian optimization, Optuna, ENCODE Hi-C, HepG2, classify\_hgvs, Local
SSIM, matrix-size dilution, per-locus threshold calibration, enhancer
proximity, tissue specificity, CTCF, CADD complementarity
